using Elements.Core;
using EnumerableToolkit;
using FrooxEngine;
using MonkeyLoader.Components;
using MonkeyLoader.Configuration;
using MonkeyLoader.Resonite.DataFeeds;

namespace MonkeyLoader.Resonite.Configuration
{
    /// <summary>
    /// Represents a config key component, which marks keys that should be
    /// enumerated in (nested) subgroups for the <see cref="SettingsDataFeed">settings</see>.
    /// </summary>
    /// <remarks><para>
    /// <see cref="LocaleString"/> keys for the subgroups are generated by appending the
    /// subgroup's path up to that point to the parent <see cref="ConfigSection"/>'s
    /// <see cref="ConfigSection.FullId">FullId</see>, all joined by periods (<c>.</c>).
    /// </para><para>
    /// This component can be added to multiple config keys, as it does not keep a reference to them.
    /// </para></remarks>
    public class ConfigKeySubgroup : IConfigKeySubgroup
    {
        /// <inheritdoc/>
        public int Priority { get; }

        /// <inheritdoc/>
        public Sequence<string> SubgroupPath { get; }

        /// <summary>
        /// Creates a new <see cref="IConfigKeySubgroup"/> component, which marks keys that should be
        /// enumerated in (nested) subgroups for the <see cref="SettingsDataFeed">settings</see>.
        /// </summary>
        /// <param name="priority">The priority of this subgroup. Higher comes first.</param>
        /// <param name="path">The first segment of the subgroup path.</param>
        /// <param name="subgroupPath">The further subgroup path elements.</param>
        /// <exception cref="ArgumentException">When any subgroup path element is <see cref="string.IsNullOrWhiteSpace(string?)"><see langword="null"/> or whitespace</see>.</exception>
        /// <inheritdoc cref="ConfigKeySubgroup"/>
        public ConfigKeySubgroup(int priority, string path, params string[]? subgroupPath)
            : this(priority, path.Yield().Concat(subgroupPath ?? []))
        { }

        /// <param name="priority">The priority of this subgroup. Higher comes first.</param>
        /// <param name="subgroupPath">The path that this subgroup should have. Must have at least one element.</param>
        /// <exception cref="NullReferenceException">When the <paramref name="subgroupPath"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentOutOfRangeException">When the <paramref name="subgroupPath"/> doesn't have at least one element.</exception>
        /// <inheritdoc cref="ConfigKeySubgroup(int, string, string[])"/>
        public ConfigKeySubgroup(int priority, IEnumerable<string> subgroupPath)
        {
            ArgumentNullException.ThrowIfNull(subgroupPath);

            Priority = priority;
            SubgroupPath = subgroupPath.ToArray();

            ArgumentOutOfRangeException.ThrowIfZero(SubgroupPath.Length, nameof(subgroupPath));

            if (SubgroupPath.Any(string.IsNullOrWhiteSpace))
                throw new ArgumentException("Subgroup path must not have any null or whitespace elements!");
        }

        /// <inheritdoc cref="ConfigKeySubgroup(int, string, string[])"/>
        public ConfigKeySubgroup(string path, params string[]? subgroupPath)
            : this(0, path.Yield().Concat(subgroupPath ?? []))
        { }

        void IComponent<IDefiningConfigKey>.Initialize(IDefiningConfigKey entity)
        { }
    }

    /// <summary>
    /// Defines the interface for config key components, which mark keys that should be
    /// enumerated in (nested) subgroups for the <see cref="SettingsDataFeed">settings</see>.
    /// </summary>
    /// <remarks>
    /// <see cref="LocaleString"/> keys for the subgroups are generated by appending the
    /// subgroup's path up to that point to the parent <see cref="ConfigSection"/>'s
    /// <see cref="ConfigSection.FullId">FullId</see>, all joined by periods (<c>.</c>).
    /// </remarks>
    public interface IConfigKeySubgroup : IConfigKeyComponent<IDefiningConfigKey>, ISubgroupedDataFeedItem, IPrioritizable
    { }
}