using Elements.Core;
using EnumerableToolkit;
using FrooxEngine;
using MonkeyLoader.Meta;

namespace MonkeyLoader.Resonite.DataFeeds
{
    /// <summary>
    /// Defines the interface for objects that should be enumerated in (nested) subgroups for their <see cref="IDataFeed">data feed</see>.
    /// </summary>
    /// <remarks>
    /// <see cref="LocaleString"/> keys for the subgroups are generated by appending the
    /// subgroup's path up to that point to the parent <see cref="IIdentifiable"/>'s
    /// <see cref="IIdentifiable.FullId">FullId</see>, followed by <c>Name</c>
    /// or <c>Description</c>, all joined by periods (<c>.</c>).<br/>
    /// <i>For example:</i> <c>Mod.Id.Config.MyConfigSection.Subgroup.NestedSubgroup.Name</c>
    /// </remarks>
    public interface ISubgroupedDataFeedItem
    {
        /// <summary>
        /// Gets the path that the subgroup of this object should have.<br/>
        /// Multiple segments are generated as nested subgroups.
        /// </summary>
        /// <inheritdoc cref="ISubgroupedDataFeedItem"/>
        public Sequence<string> SubgroupPath { get; }
    }
}