using Elements.Core;
using EnumerableToolkit;
using FrooxEngine;
using MonkeyLoader.Meta;

#pragma warning disable CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)

namespace MonkeyLoader.Resonite.DataFeeds
{
    /// <summary>
    /// Represents a helper to generate nested <see cref="DataFeedGroup">subgroups</see>
    /// for <see cref="ISubgroupedDataFeedItem">subgrouped data feed items</see>.
    /// </summary>
    /// <remarks><para>
    /// The generator uses internal state to track which subgroups have already been created.<br/>
    /// As such, it must be recreated for each enumeration of a <see cref="IDataFeed">data feed</see>.
    /// </para><para>
    /// <see cref="LocaleString"/> keys for the subgroups are generated by appending the
    /// subgroup's path up to that point to the <see cref="BaseIdentifiable">BaseIdentifiable</see>'s
    /// <see cref="IIdentifiable.FullId">FullId</see>, all joined by periods (<c>.</c>).
    /// </para></remarks>
    public sealed class SubgroupGenerator
    {
        private readonly HashSet<Sequence<string>> _createdSubgroups = [];

        /// <summary>
        /// Gets the group keys for the outer container that the
        /// nested <see cref="DataFeedGroup">subgroups</see> should be placed in.
        /// </summary>
        public IReadOnlyList<string> BaseGroupKeys { get; }

        /// <summary>
        /// Gets the base <see cref="IIdentifiable">identifiable</see> that's used to
        /// generate the <see cref="LocaleString"/>s for the subgroups.
        /// </summary>
        /// <remarks>
        /// <see cref="LocaleString"/> keys for the subgroups are generated by appending the
        /// subgroup's path up to that point to the this <see cref="IIdentifiable">identifiable</see>'s
        /// <see cref="IIdentifiable.FullId">FullId</see>, all joined by periods (<c>.</c>).
        /// </remarks>
        public IIdentifiable BaseIdentifiable { get; }

        /// <summary>
        /// Gets path of the items being enumerated.
        /// </summary>
        public IReadOnlyList<string> Path { get; }

        /// <summary>
        /// Creates a new instance of this helper to generate nested <see cref="DataFeedGroup">subgroups</see>
        /// for <see cref="ISubgroupedDataFeedItem">subgrouped data feed items</see>.
        /// </summary>
        /// <param name="baseIdentifiable">The base <see cref="IIdentifiable">identifiable</see> that's used to generate the <see cref="LocaleString"/>s for the subgroups.</param>
        /// <param name="path">The path of the items being enumerated.</param>
        /// <param name="groupKeys">The group keys for the outer container that the nested <see cref="DataFeedGroup">subgroups</see> should be placed in.</param>
        /// <inheritdoc cref="SubgroupGenerator"/>
        public SubgroupGenerator(IIdentifiable baseIdentifiable, IReadOnlyList<string> path, IReadOnlyList<string> groupKeys)
        {
            BaseIdentifiable = baseIdentifiable;
            Path = path;
            BaseGroupKeys = groupKeys;
        }

        /// <summary>
        /// Enumerates the missing nested subgroups for the given path.
        /// </summary>
        /// <remarks>
        /// Prefer using any of the <c>GetSubgroupEnumerator</c> overloads,
        /// since they also return the required group keys to place items in the final subgroup.
        /// </remarks>
        /// <inheritdoc cref="GetSubgroupEnumerator(Sequence{string}, int, out IReadOnlyList{string})"/>
        public async IAsyncEnumerable<DataFeedItem> EnumerateSubgroupsAsync(Sequence<string> subgroupPath, int priority = 0)
        {
            await Task.CompletedTask;

            if (_createdSubgroups.Contains(subgroupPath))
                yield break;

            for (var i = 0; i < subgroupPath.Length; ++i)
            {
                var subgroupPathElements = subgroupPath.Take(i + 1).ToArray();

                if (!_createdSubgroups.Add(subgroupPathElements))
                    continue;

                var joinedSubgroupPath = string.Join('.', subgroupPathElements);
                var label = BaseIdentifiable.GetLocaleString($"{joinedSubgroupPath}.Name");
                var description = BaseIdentifiable.GetLocaleString($"{joinedSubgroupPath}.Description");

                var subgroup = new DataFeedGroup();
                subgroup.InitBase(subgroupPathElements[i], Path, [.. BaseGroupKeys, .. subgroupPathElements[..i]], label);
                subgroup.InitSorting(-priority);
                subgroup.InitDescription(description);
                yield return subgroup;
            }
        }

        /// <summary>
        /// Gets an enumerator for the missing nested subgroups for the subgrouped data feed item's path and
        /// returns the group keys necessary to place items in the final subgroup,
        /// using the item's <see cref="IPrioritizable.Priority">priority</see> too, if available.
        /// </summary>
        /// <param name="subgroupedItem">
        /// The <see cref="ISubgroupedDataFeedItem">subgrouped data feed item</see> containing the
        /// <see cref="ISubgroupedDataFeedItem.SubgroupPath">path</see> of the required nested subgroups.<br/>
        /// If this is also <see cref="IPrioritizable"/>, that <see cref="IPrioritizable.Priority">priority</see>
        /// will be assigned to the newly generated subgroups; otherwise, zero. Higher comes first.
        /// </param>
        /// <inheritdoc cref="GetSubgroupEnumerator(ISubgroupedDataFeedItem, int, out IReadOnlyList{string})"/>
        public IAsyncEnumerable<DataFeedItem> GetSubgroupEnumerator(ISubgroupedDataFeedItem subgroupedItem, out IReadOnlyList<string> groupKeys)
            => GetSubgroupEnumerator(subgroupedItem, (subgroupedItem as IPrioritizable)?.Priority ?? 0, out groupKeys);

        /// <summary>
        /// Gets an enumerator for the missing nested subgroups for the subgrouped data feed item's path and
        /// returns the group keys necessary to place items in the final subgroup.
        /// </summary>
        /// <param name="subgroupedItem">
        /// The <see cref="ISubgroupedDataFeedItem">subgrouped data feed item</see> containing the
        /// <see cref="ISubgroupedDataFeedItem.SubgroupPath">path</see> of the required nested subgroups.
        /// </param>
        /// <inheritdoc cref="GetSubgroupEnumerator(Sequence{string}, int, out IReadOnlyList{string})"/>
        public IAsyncEnumerable<DataFeedItem> GetSubgroupEnumerator(ISubgroupedDataFeedItem subgroupedItem, int priority, out IReadOnlyList<string> groupKeys)
        {
            groupKeys = [.. BaseGroupKeys, .. subgroupedItem.SubgroupPath];

            return EnumerateSubgroupsAsync(subgroupedItem.SubgroupPath, priority);
        }

        /// <summary>
        /// Gets an enumerator for the missing nested subgroups for the given path and
        /// returns the group keys necessary to place items in the final subgroup.
        /// </summary>
        /// <param name="subgroupPath">The path of the required nested subgroups.</param>
        /// <param name="priority">The optional priority to assign to the newly created subgroups. Higher comes first.</param>
        /// <param name="groupKeys">The group keys necessary to place items in the final subgroup.</param>
        /// <returns>A sequence of the missing nested subgroups for the given path. Empty if all subgroups have already been generated.</returns>
        public IAsyncEnumerable<DataFeedItem> GetSubgroupEnumerator(Sequence<string> subgroupPath, int priority, out IReadOnlyList<string> groupKeys)
        {
            groupKeys = [.. BaseGroupKeys, .. subgroupPath];

            return EnumerateSubgroupsAsync(subgroupPath, priority);
        }

        /// <inheritdoc cref="GetSubgroupEnumerator(Sequence{string}, int, out IReadOnlyList{string})"/>
        public IAsyncEnumerable<DataFeedItem> GetSubgroupEnumerator(Sequence<string> subgroupPath, out IReadOnlyList<string> groupKeys)
            => GetSubgroupEnumerator(subgroupPath, 0, out groupKeys);
    }
}

#pragma warning restore CS1573 // Parameter has no matching param tag in the XML comment (but other parameters do)